import { test, expect } from '@playwright/test';
import { dragAndDropFile } from './utils/DragAndDropFile';

test('test', async ({ page }) => {
  test.setTimeout(120000);
  await page.goto('http://localhost:3000/');
  await page.getByPlaceholder('Search blueprints..').click();

  // search for the twitter blueprint
  await page.getByPlaceholder('Search blueprints..').fill('twit');
  await page.getByRole('link', { name: 'Twitter test 3 Compiled twit' }).click();

  // check the connect emails page
  await expect(page.getByRole('heading', { name: 'Connect emails' })).toBeVisible();

  // upload the email file. We need another component for this. https://stackoverflow.com/a/77738836
  await dragAndDropFile(page, '#drag-and-drop-emails', 'src/tests/assets/PasswordResetRequest.eml', 'PasswordResetRequest.eml');
  await expect(page.getByRole('img', { name: 'status' })).toBeVisible();
  await expect(page.locator('#uploadedFile')).toBeVisible();
  await page.locator('#uploadedFile').click();
  await expect(page.getByRole('button', { name: 'Add Inputs' })).toBeVisible();
  await page.getByRole('button', { name: 'Add Inputs' }).click();
  await page.getByPlaceholder('Enter Address').click();
  await page.getByPlaceholder('Enter Address').fill('0x00');
  await expect(page.getByRole('button', { name: 'Create Proof Remotely' })).toBeVisible();
  await page.getByRole('button', { name: 'Create Proof Remotely' }).click();
  
  // check the proof generation page
  await expect(page.locator('#loader')).toBeVisible(); // loader
  await page.waitForTimeout(60000);
  await expect(page.getByRole('heading', { name: 'View Proof' })).toBeVisible();
  await expect(page.locator('div').filter({ hasText: 'View ProofPlease standby,' }).nth(3)).toBeVisible();
  await expect(page.getByText('|View{"handle": "wryonik"}')).toBeVisible();
  await expect(page.getByRole('img', { name: 'status' })).toBeVisible();
  await expect(page.getByText('{"handle": "wryonik"}')).toBeVisible();
  await expect(page.getByRole('link', { name: '| View' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'download' })).toBeVisible();
  const proofInfoPagePromise = page.waitForEvent('popup');

  // go to the proof info page
  await page.getByRole('link', { name: '| View' }).click();

  // check values in the proof info page
  const proofInfoPage = await proofInfoPagePromise;
  await expect(proofInfoPage.locator('#job-id')).toBeVisible();
  await expect(proofInfoPage.locator('#job-id')).not.toBeNull();
  await expect(proofInfoPage.locator('#blueprint-title')).not.toHaveText('-');
  await expect(proofInfoPage.locator('#outputs')).not.toHaveText('-');
  await expect(proofInfoPage.locator('#date-created')).not.toHaveText('-');
  await expect(proofInfoPage.locator('#time-taken')).not.toHaveText('-');
  await expect(proofInfoPage.locator('#status')).not.toHaveText('-');
  await expect(proofInfoPage.getByRole('button', { name: 'Share proof Share Proof' })).toBeVisible();
  await expect(proofInfoPage.locator('div').filter({ hasText: '{ "pi_a": [ "' }).nth(3)).toBeVisible();
  await expect(proofInfoPage.locator('#email-render')).toBeVisible();
  await proofInfoPage.close();

  // check its value to be populated in the past proofs page
  await page.getByRole('button', { name: 'commit Past proofs' }).click();
  await expect(page.getByText('Past ProofsAll the proofs generated by you using this blueprint Proof')).toBeVisible();
});