import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from 'next-themes';
import { Fustat } from 'next/font/google';
import AuthHandler from './components/AuthHandler';
import GoogleAuthProvider from './contexts/GoogleAuthProvider';
import { GoogleOAuthProvider } from '@react-oauth/google';
import ToastProvider from './contexts/ToastProvider';

const fustat = Fustat({ subsets: ['latin'] });

// TODO: Adjust to zk email registry
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fustat.className} flex min-h-screen flex-col bg-[#F5F3EF] antialiased`}>
        <ThemeProvider attribute="class">
          <GoogleOAuthProvider clientId={process.env.GOOGLE_CLIENT_ID || ''}>
            <GoogleAuthProvider>
              <ToastProvider>
                <AuthHandler />
                {children}
              </ToastProvider>
            </GoogleAuthProvider>
          </GoogleOAuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
