import type { Metadata } from 'next';
import './globals.css';
import Navbar from '@/app/components/Navbar';
import Footer from '@/app/components/Footer';
import { ThemeProvider } from 'next-themes';
import { Fustat } from 'next/font/google';
import AuthHandler from './components/AuthHandler';

const fustat = Fustat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fustat.className} flex min-h-screen flex-col bg-[#F5F3EF] antialiased`}>
        <ThemeProvider attribute="class">
          <AuthHandler />
          <Navbar />
          <div className="mx-auto w-full flex-grow md:w-[768px]">{children}</div>
          <div className="mt-auto">
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
