'use client';

import ProofStatusTable from '@/app/components/ProofStatusTable';
import { use, useEffect } from 'react';
import { useProofStore } from '../store';
import sdk from '@/lib/sdk';
import { useProofEmailStore } from '@/lib/stores/useProofEmailStore';
import { BlueprintTitle } from '@/app/components/BlueprintTitle';
import Loader from '@/components/ui/loader';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import Image from 'next/image';
import { Status } from '@zk-email/sdk';

const Proofs = ({ params }: { params: Promise<{ id: string }> }) => {
  const { id } = use(params);
  const {
    reset,
    blueprint,
    setBlueprint,
    isUserStarred,
    starBlueprint,
    unStarBlueprint,
    setIsUserStarred,
  } = useProofStore();
  const { getProofIdsForBlueprint } = useProofEmailStore();

  useEffect(() => {
    reset();

    sdk
      .getBlueprintById(id)
      .then(async (bp) => {
        await bp.getStars();
        setBlueprint(bp);
        await setIsUserStarred();
      })
      .catch((err) => {
        console.error(`Failed to blueprint with id ${id}: `, err);
      });
  }, []);

  if (!blueprint) {
    return (
      <div className="flex h-screen items-center justify-center">
        <Loader />
      </div>
    );
  }

  return (
    <div className="mx-auto flex flex-col py-16">
      <Link href={blueprint?.props.status === Status.Draft ? `/` : `/${id}`}>
        <Button
          variant="ghost"
          startIcon={
            <Image
              src="/assets/ArrowLeft.svg"
              alt="back"
              width={16}
              height={16}
              style={{
                maxWidth: '100%',
                height: 'auto',
              }}
            />
          }
        >
          {blueprint?.props.title}
        </Button>
      </Link>
      <div className="flex flex-col gap-10">
        <BlueprintTitle
          blueprint={blueprint}
          isUserStarred={isUserStarred}
          unStarBlueprint={unStarBlueprint}
          starBlueprint={starBlueprint}
        />

        <div className="flex flex-col gap-6 rounded-3xl border border-grey-500 bg-white p-6 shadow-[2px_4px_2px_0px_rgba(0,0,0,0.02),_2px_3px_4.5px_0px_rgba(0,0,0,0.07)]">
          <div className="flex flex-col items-center justify-center gap-6">
            <div className="flex w-full flex-col gap-1">
              <h4 className="text-xl font-bold text-grey-800">Past Proofs</h4>
              <p className="text-base font-medium text-grey-700">
                All the proofs generated by you using this blueprint{' '}
              </p>
            </div>
            <ProofStatusTable proofs={getProofIdsForBlueprint(id)} />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Proofs;
